package com.prog.service.maintenancemanagement;

import java.util.List;

import java.util.Map;
import java.util.Random;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.prog.Dao.maintenancemanagement.BreakdownMaintenanceReportDao;
import com.prog.model.erp.BreakdownMaintenanceReport;
import com.prog.model.erp.Employee;
import com.prog.model.erp.EquipmentMaster;

@Service
public class BreakdownMaintenanceReportService {
	@Autowired
	private BreakdownMaintenanceReportDao breakdownMaintenanceReportDao;
	// Save a new breakdown report with autogenerated UID
    public int saveBreakdownMaintenanceReport(BreakdownMaintenanceReport report) {
        String breakdownUid = generateBreakdownUid();
        report.setBreakdownmaintenancereportuid(breakdownUid);
        return breakdownMaintenanceReportDao.saveBreakdownMaintenanceReport(report);
    }
    
    // Update an existing breakdown report
    public int updateBreakdownMaintenanceReport(BreakdownMaintenanceReport report) {
        return breakdownMaintenanceReportDao.updateBreakdownMaintenanceReport(report);
    }

    // Get a breakdown report by its ID
    public BreakdownMaintenanceReport getBreakdownMaintenanceReportById(Long id) {
        return breakdownMaintenanceReportDao.getBreakdownMaintenanceReportById(id);
    }

    // Get all breakdown maintenance reports
    public List<Map<String,Object>> getAllBreakdownMaintenanceReportData() {
        return breakdownMaintenanceReportDao.getAllBreakdownMaintenanceReportData();
    }

    // Delete a report by ID
    public void deleteBreakdownMaintenanceReportById(Long id) {
    	breakdownMaintenanceReportDao.deleteBreakdownMaintenanceReportById(id);
    }

    
    // Generate a unique breakdown report UID
    private String generateBreakdownUid() {
        Random random = new Random();
        int number = 1000 + random.nextInt(9000);
        return "BMR" + number;
    }
    
	public List<String> getEquipmentDetailsById(){
		return breakdownMaintenanceReportDao.getEquipmentDetailsById();
	}
	
	public EquipmentMaster getEquipmentDetails(String equipmentuid) {
		return breakdownMaintenanceReportDao.getEquipmentDetails(equipmentuid);
	}
	
	public List<String> getEmployeeDetailsById(){
		return breakdownMaintenanceReportDao.getEmployeeDetailsById();
	}
	
	public Employee getEmployeeDetails(String employeeuid) {
		return breakdownMaintenanceReportDao.getEmployeeDetails(employeeuid);
	}
}
