package com.prog.service.inventory;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.prog.Dao.inventory.RawmaterialDeliveryChallanDao;
import com.prog.model.erp.Rawmaterialdeliverychallan;
import com.prog.model.erp.Rawmaterialpurchaseorder;

import java.util.List;
import java.util.Map;
import java.util.Random;

@Service
public class RawmaterialDeliveryChallanService {

    @Autowired
    private RawmaterialDeliveryChallanDao rawmaterialDeliveryChallanDao;

    // Save a new delivery challan with autogenerated challan number
    public int saveDeliveryChallan(Rawmaterialdeliverychallan challan) {
        String uid = generateChallanNumber();
        challan.setRawmaterialdeliverychallanuid(uid);
        return rawmaterialDeliveryChallanDao.saveDeliveryChallan(challan);
    }

    // Update an existing delivery challan
    public int updateDeliveryChallan(Rawmaterialdeliverychallan challan) {
        return rawmaterialDeliveryChallanDao.updateDeliveryChallan(challan);
    }

    // Delete a challan by its ID
    public void deleteDeliveryChallan(Long id) {
        rawmaterialDeliveryChallanDao.deleteDeliveryChallan(id);
    }

    // Fetch a single challan by its ID
    public Rawmaterialdeliverychallan getChallanById(Long id) {
        return rawmaterialDeliveryChallanDao.getChallanById(id);
    }

    // Fetch all challans
    public List<Map<String, Object>> getAllChallans() {
        return rawmaterialDeliveryChallanDao.getAllChallans();
    }

    // Generate a random challan number (e.g., DCH1234)
    private String generateChallanNumber() {
    	int length = 4;
        String characters = "0123456789";
        Random random = new Random();
        StringBuilder uid = new StringBuilder("RMDCH");

        for (int i = 0; i < length; i++) {
            uid.append(characters.charAt(random.nextInt(characters.length())));
        }

        return uid.toString();
    }
    
        

    // Get raw material PO details by UID (AJAX)
    public Rawmaterialpurchaseorder getPurchaseOrderDetails(String uid) {
        return rawmaterialDeliveryChallanDao.getPurchaseOrderDetailsByUid(uid);
    }

    // Get all raw material PO UIDs (for dropdown)
    public List<String> getAllPurchaseOrderUIDs() {
        return rawmaterialDeliveryChallanDao.getAllPurchaseOrderUIDs();
    }

    // Get list of all employees (UID + name) for dropdown
//    public List<Map<String, String>> getAllEmployees() {
//        return rawmaterialDeliveryChallanDao.getAllEmployees();
//    }

    // Get employee name by UID (for AJAX population)
    public Map<String, String> getEmployeeNameByUid(String uid) {
        return rawmaterialDeliveryChallanDao.getEmployeeNameByUid(uid);
    }
    
    public List<Map<String, String>> getAllEmployees() {
        return rawmaterialDeliveryChallanDao.getAllEmployees();
    }
    
    
}
